# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tombalaGameUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1072, 847)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 111, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 101, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 170, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(100, 170, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 170, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(70, 200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(100, 200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(40, 230, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 230, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(40, 260, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(100, 230, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(70, 230, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(70, 260, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAutoFillBackground(False)
        self.label_18.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(100, 260, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAutoFillBackground(False)
        self.label_19.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(40, 290, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setAutoFillBackground(False)
        self.label_20.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 290, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setAutoFillBackground(False)
        self.label_21.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(10, 320, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAutoFillBackground(False)
        self.label_22.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(40, 320, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAutoFillBackground(False)
        self.label_23.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(100, 290, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setAutoFillBackground(False)
        self.label_24.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(70, 290, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setAutoFillBackground(False)
        self.label_25.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(70, 320, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setAutoFillBackground(False)
        self.label_26.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(100, 320, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setAutoFillBackground(False)
        self.label_27.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(100, 440, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setAutoFillBackground(False)
        self.label_28.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(10, 440, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setAutoFillBackground(False)
        self.label_29.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(100, 470, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setAutoFillBackground(False)
        self.label_30.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(100, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setAutoFillBackground(False)
        self.label_31.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(40, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setAutoFillBackground(False)
        self.label_32.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(10, 500, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setAutoFillBackground(False)
        self.label_33.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(10, 470, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setAutoFillBackground(False)
        self.label_34.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(70, 410, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setAutoFillBackground(False)
        self.label_35.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(40, 500, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setAutoFillBackground(False)
        self.label_36.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(10, 410, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setAutoFillBackground(False)
        self.label_37.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(70, 500, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setAutoFillBackground(False)
        self.label_38.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(10, 350, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setAutoFillBackground(False)
        self.label_39.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(40, 410, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setAutoFillBackground(False)
        self.label_40.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(40, 470, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setAutoFillBackground(False)
        self.label_41.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(10, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(False)
        self.label_42.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_43 = QtGui.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(100, 350, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setAutoFillBackground(False)
        self.label_43.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(70, 440, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setAutoFillBackground(False)
        self.label_44.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(40, 440, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setAutoFillBackground(False)
        self.label_45.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(70, 350, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setAutoFillBackground(False)
        self.label_46.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtGui.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(40, 350, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setAutoFillBackground(False)
        self.label_47.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_48 = QtGui.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(100, 410, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setAutoFillBackground(False)
        self.label_48.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_49 = QtGui.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(70, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setAutoFillBackground(False)
        self.label_49.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(70, 470, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setAutoFillBackground(False)
        self.label_50.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_51 = QtGui.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(100, 500, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setAutoFillBackground(False)
        self.label_51.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtGui.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(130, 500, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setAutoFillBackground(False)
        self.label_52.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_53 = QtGui.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(130, 320, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setAutoFillBackground(False)
        self.label_53.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_54 = QtGui.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(130, 470, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setAutoFillBackground(False)
        self.label_54.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(130, 200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setAutoFillBackground(False)
        self.label_55.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(130, 230, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setAutoFillBackground(False)
        self.label_56.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_57 = QtGui.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(130, 410, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_57.setFont(font)
        self.label_57.setAutoFillBackground(False)
        self.label_57.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_58 = QtGui.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(130, 260, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_58.setFont(font)
        self.label_58.setAutoFillBackground(False)
        self.label_58.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_59 = QtGui.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(130, 170, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_59.setFont(font)
        self.label_59.setAutoFillBackground(False)
        self.label_59.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_60 = QtGui.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(130, 440, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_60.setFont(font)
        self.label_60.setAutoFillBackground(False)
        self.label_60.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.label_61 = QtGui.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(130, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_61.setFont(font)
        self.label_61.setAutoFillBackground(False)
        self.label_61.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtGui.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(130, 290, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_62.setFont(font)
        self.label_62.setAutoFillBackground(False)
        self.label_62.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.label_63 = QtGui.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(130, 350, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_63.setFont(font)
        self.label_63.setAutoFillBackground(False)
        self.label_63.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(40, 680, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_64.setFont(font)
        self.label_64.setAutoFillBackground(False)
        self.label_64.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_65 = QtGui.QLabel(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(70, 680, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_65.setFont(font)
        self.label_65.setAutoFillBackground(False)
        self.label_65.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_66 = QtGui.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(130, 680, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_66.setFont(font)
        self.label_66.setAutoFillBackground(False)
        self.label_66.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_67 = QtGui.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(40, 710, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_67.setFont(font)
        self.label_67.setAutoFillBackground(False)
        self.label_67.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_68 = QtGui.QLabel(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(130, 650, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_68.setFont(font)
        self.label_68.setAutoFillBackground(False)
        self.label_68.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.label_69 = QtGui.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(40, 650, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_69.setFont(font)
        self.label_69.setAutoFillBackground(False)
        self.label_69.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.label_70 = QtGui.QLabel(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(10, 740, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_70.setFont(font)
        self.label_70.setAutoFillBackground(False)
        self.label_70.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_71 = QtGui.QLabel(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(70, 650, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_71.setFont(font)
        self.label_71.setAutoFillBackground(False)
        self.label_71.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.label_72 = QtGui.QLabel(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(10, 590, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_72.setFont(font)
        self.label_72.setAutoFillBackground(False)
        self.label_72.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.label_73 = QtGui.QLabel(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(70, 590, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_73.setFont(font)
        self.label_73.setAutoFillBackground(False)
        self.label_73.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_74 = QtGui.QLabel(self.centralwidget)
        self.label_74.setGeometry(QtCore.QRect(10, 680, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_74.setFont(font)
        self.label_74.setAutoFillBackground(False)
        self.label_74.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.label_75 = QtGui.QLabel(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(100, 650, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_75.setFont(font)
        self.label_75.setAutoFillBackground(False)
        self.label_75.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.label_76 = QtGui.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(130, 620, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_76.setFont(font)
        self.label_76.setAutoFillBackground(False)
        self.label_76.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.label_77 = QtGui.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(130, 560, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_77.setFont(font)
        self.label_77.setAutoFillBackground(False)
        self.label_77.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.label_78 = QtGui.QLabel(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(130, 530, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_78.setFont(font)
        self.label_78.setAutoFillBackground(False)
        self.label_78.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.label_79 = QtGui.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(70, 530, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_79.setFont(font)
        self.label_79.setAutoFillBackground(False)
        self.label_79.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.label_80 = QtGui.QLabel(self.centralwidget)
        self.label_80.setGeometry(QtCore.QRect(10, 710, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_80.setFont(font)
        self.label_80.setAutoFillBackground(False)
        self.label_80.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.label_81 = QtGui.QLabel(self.centralwidget)
        self.label_81.setGeometry(QtCore.QRect(70, 710, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_81.setFont(font)
        self.label_81.setAutoFillBackground(False)
        self.label_81.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.label_82 = QtGui.QLabel(self.centralwidget)
        self.label_82.setGeometry(QtCore.QRect(10, 560, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_82.setFont(font)
        self.label_82.setAutoFillBackground(False)
        self.label_82.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.label_83 = QtGui.QLabel(self.centralwidget)
        self.label_83.setGeometry(QtCore.QRect(10, 620, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_83.setFont(font)
        self.label_83.setAutoFillBackground(False)
        self.label_83.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.label_84 = QtGui.QLabel(self.centralwidget)
        self.label_84.setGeometry(QtCore.QRect(70, 740, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_84.setFont(font)
        self.label_84.setAutoFillBackground(False)
        self.label_84.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.label_85 = QtGui.QLabel(self.centralwidget)
        self.label_85.setGeometry(QtCore.QRect(130, 710, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_85.setFont(font)
        self.label_85.setAutoFillBackground(False)
        self.label_85.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.label_86 = QtGui.QLabel(self.centralwidget)
        self.label_86.setGeometry(QtCore.QRect(100, 740, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_86.setFont(font)
        self.label_86.setAutoFillBackground(False)
        self.label_86.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.label_87 = QtGui.QLabel(self.centralwidget)
        self.label_87.setGeometry(QtCore.QRect(40, 740, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_87.setFont(font)
        self.label_87.setAutoFillBackground(False)
        self.label_87.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.label_88 = QtGui.QLabel(self.centralwidget)
        self.label_88.setGeometry(QtCore.QRect(10, 530, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_88.setFont(font)
        self.label_88.setAutoFillBackground(False)
        self.label_88.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.label_89 = QtGui.QLabel(self.centralwidget)
        self.label_89.setGeometry(QtCore.QRect(130, 740, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_89.setFont(font)
        self.label_89.setAutoFillBackground(False)
        self.label_89.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.label_90 = QtGui.QLabel(self.centralwidget)
        self.label_90.setGeometry(QtCore.QRect(130, 590, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_90.setFont(font)
        self.label_90.setAutoFillBackground(False)
        self.label_90.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.label_91 = QtGui.QLabel(self.centralwidget)
        self.label_91.setGeometry(QtCore.QRect(100, 680, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_91.setFont(font)
        self.label_91.setAutoFillBackground(False)
        self.label_91.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.label_92 = QtGui.QLabel(self.centralwidget)
        self.label_92.setGeometry(QtCore.QRect(70, 620, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_92.setFont(font)
        self.label_92.setAutoFillBackground(False)
        self.label_92.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.label_93 = QtGui.QLabel(self.centralwidget)
        self.label_93.setGeometry(QtCore.QRect(100, 590, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_93.setFont(font)
        self.label_93.setAutoFillBackground(False)
        self.label_93.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.label_94 = QtGui.QLabel(self.centralwidget)
        self.label_94.setGeometry(QtCore.QRect(40, 590, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_94.setFont(font)
        self.label_94.setAutoFillBackground(False)
        self.label_94.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.label_95 = QtGui.QLabel(self.centralwidget)
        self.label_95.setGeometry(QtCore.QRect(40, 530, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_95.setFont(font)
        self.label_95.setAutoFillBackground(False)
        self.label_95.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.label_96 = QtGui.QLabel(self.centralwidget)
        self.label_96.setGeometry(QtCore.QRect(100, 710, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_96.setFont(font)
        self.label_96.setAutoFillBackground(False)
        self.label_96.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.label_97 = QtGui.QLabel(self.centralwidget)
        self.label_97.setGeometry(QtCore.QRect(70, 560, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_97.setFont(font)
        self.label_97.setAutoFillBackground(False)
        self.label_97.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.label_98 = QtGui.QLabel(self.centralwidget)
        self.label_98.setGeometry(QtCore.QRect(100, 620, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_98.setFont(font)
        self.label_98.setAutoFillBackground(False)
        self.label_98.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_99 = QtGui.QLabel(self.centralwidget)
        self.label_99.setGeometry(QtCore.QRect(100, 530, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_99.setFont(font)
        self.label_99.setAutoFillBackground(False)
        self.label_99.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.label_100 = QtGui.QLabel(self.centralwidget)
        self.label_100.setGeometry(QtCore.QRect(10, 650, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_100.setFont(font)
        self.label_100.setAutoFillBackground(False)
        self.label_100.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.label_101 = QtGui.QLabel(self.centralwidget)
        self.label_101.setGeometry(QtCore.QRect(40, 620, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_101.setFont(font)
        self.label_101.setAutoFillBackground(False)
        self.label_101.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.label_102 = QtGui.QLabel(self.centralwidget)
        self.label_102.setGeometry(QtCore.QRect(40, 560, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_102.setFont(font)
        self.label_102.setAutoFillBackground(False)
        self.label_102.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.label_103 = QtGui.QLabel(self.centralwidget)
        self.label_103.setGeometry(QtCore.QRect(100, 560, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_103.setFont(font)
        self.label_103.setAutoFillBackground(False)
        self.label_103.setStyleSheet(_fromUtf8("background-color:yellow;"))
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(190, 490, 701, 271))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(180, 40, 841, 141))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.label_104 = QtGui.QLabel(self.centralwidget)
        self.label_104.setGeometry(QtCore.QRect(490, 200, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_104.setFont(font)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.label_105 = QtGui.QLabel(self.centralwidget)
        self.label_105.setGeometry(QtCore.QRect(190, 250, 180, 180))
        self.label_105.setText(_fromUtf8(""))
        self.label_105.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Users/User/Desktop/1.jpg")))
        self.label_105.setScaledContents(True)
        self.label_105.setWordWrap(False)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(900, 490, 151, 271))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_106 = QtGui.QLabel(self.centralwidget)
        self.label_106.setGeometry(QtCore.QRect(410, 250, 180, 180))
        self.label_106.setText(_fromUtf8(""))
        self.label_106.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Users/User/Desktop/4.jpg")))
        self.label_106.setScaledContents(True)
        self.label_106.setAlignment(QtCore.Qt.AlignCenter)
        self.label_106.setWordWrap(False)
        self.label_106.setIndent(-1)
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.label_108 = QtGui.QLabel(self.centralwidget)
        self.label_108.setGeometry(QtCore.QRect(830, 250, 180, 180))
        self.label_108.setLineWidth(1)
        self.label_108.setText(_fromUtf8(""))
        self.label_108.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Users/User/Desktop/3.jpg")))
        self.label_108.setScaledContents(True)
        self.label_108.setWordWrap(False)
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.label_107 = QtGui.QLabel(self.centralwidget)
        self.label_107.setGeometry(QtCore.QRect(620, 250, 180, 180))
        self.label_107.setText(_fromUtf8(""))
        self.label_107.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Users/User/Desktop/21.jpg")))
        self.label_107.setScaledContents(True)
        self.label_107.setAlignment(QtCore.Qt.AlignCenter)
        self.label_107.setWordWrap(False)
        self.label_107.setIndent(-1)
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.label_109 = QtGui.QLabel(self.centralwidget)
        self.label_109.setGeometry(QtCore.QRect(220, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_109.setFont(font)
        self.label_109.setAlignment(QtCore.Qt.AlignCenter)
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.label_110 = QtGui.QLabel(self.centralwidget)
        self.label_110.setGeometry(QtCore.QRect(440, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_110.setFont(font)
        self.label_110.setAlignment(QtCore.Qt.AlignCenter)
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.label_111 = QtGui.QLabel(self.centralwidget)
        self.label_111.setGeometry(QtCore.QRect(650, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_111.setFont(font)
        self.label_111.setAlignment(QtCore.Qt.AlignCenter)
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.label_112 = QtGui.QLabel(self.centralwidget)
        self.label_112.setGeometry(QtCore.QRect(870, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_112.setFont(font)
        self.label_112.setAlignment(QtCore.Qt.AlignCenter)
        self.label_112.setObjectName(_fromUtf8("label_112"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Selected Number", None))
        self.label_2.setText(_translate("MainWindow", "99", None))
        self.label_3.setText(_translate("MainWindow", "Picked Numbers", None))
        self.label_4.setText(_translate("MainWindow", "1", None))
        self.label_5.setText(_translate("MainWindow", "1", None))
        self.label_6.setText(_translate("MainWindow", "1", None))
        self.label_7.setText(_translate("MainWindow", "1", None))
        self.label_8.setText(_translate("MainWindow", "1", None))
        self.label_9.setText(_translate("MainWindow", "1", None))
        self.label_10.setText(_translate("MainWindow", "1", None))
        self.label_11.setText(_translate("MainWindow", "1", None))
        self.label_12.setText(_translate("MainWindow", "1", None))
        self.label_13.setText(_translate("MainWindow", "1", None))
        self.label_14.setText(_translate("MainWindow", "1", None))
        self.label_15.setText(_translate("MainWindow", "1", None))
        self.label_16.setText(_translate("MainWindow", "1", None))
        self.label_17.setText(_translate("MainWindow", "1", None))
        self.label_18.setText(_translate("MainWindow", "1", None))
        self.label_19.setText(_translate("MainWindow", "1", None))
        self.label_20.setText(_translate("MainWindow", "1", None))
        self.label_21.setText(_translate("MainWindow", "1", None))
        self.label_22.setText(_translate("MainWindow", "1", None))
        self.label_23.setText(_translate("MainWindow", "1", None))
        self.label_24.setText(_translate("MainWindow", "99", None))
        self.label_25.setText(_translate("MainWindow", "99", None))
        self.label_26.setText(_translate("MainWindow", "99", None))
        self.label_27.setText(_translate("MainWindow", "99", None))
        self.label_28.setText(_translate("MainWindow", "1", None))
        self.label_29.setText(_translate("MainWindow", "1", None))
        self.label_30.setText(_translate("MainWindow", "99", None))
        self.label_31.setText(_translate("MainWindow", "1", None))
        self.label_32.setText(_translate("MainWindow", "1", None))
        self.label_33.setText(_translate("MainWindow", "1", None))
        self.label_34.setText(_translate("MainWindow", "1", None))
        self.label_35.setText(_translate("MainWindow", "1", None))
        self.label_36.setText(_translate("MainWindow", "1", None))
        self.label_37.setText(_translate("MainWindow", "1", None))
        self.label_38.setText(_translate("MainWindow", "99", None))
        self.label_39.setText(_translate("MainWindow", "1", None))
        self.label_40.setText(_translate("MainWindow", "1", None))
        self.label_41.setText(_translate("MainWindow", "1", None))
        self.label_42.setText(_translate("MainWindow", "1", None))
        self.label_43.setText(_translate("MainWindow", "1", None))
        self.label_44.setText(_translate("MainWindow", "1", None))
        self.label_45.setText(_translate("MainWindow", "1", None))
        self.label_46.setText(_translate("MainWindow", "1", None))
        self.label_47.setText(_translate("MainWindow", "1", None))
        self.label_48.setText(_translate("MainWindow", "1", None))
        self.label_49.setText(_translate("MainWindow", "1", None))
        self.label_50.setText(_translate("MainWindow", "99", None))
        self.label_51.setText(_translate("MainWindow", "99", None))
        self.label_52.setText(_translate("MainWindow", "99", None))
        self.label_53.setText(_translate("MainWindow", "99", None))
        self.label_54.setText(_translate("MainWindow", "99", None))
        self.label_55.setText(_translate("MainWindow", "1", None))
        self.label_56.setText(_translate("MainWindow", "1", None))
        self.label_57.setText(_translate("MainWindow", "1", None))
        self.label_58.setText(_translate("MainWindow", "1", None))
        self.label_59.setText(_translate("MainWindow", "1", None))
        self.label_60.setText(_translate("MainWindow", "1", None))
        self.label_61.setText(_translate("MainWindow", "1", None))
        self.label_62.setText(_translate("MainWindow", "99", None))
        self.label_63.setText(_translate("MainWindow", "1", None))
        self.label_64.setText(_translate("MainWindow", "1", None))
        self.label_65.setText(_translate("MainWindow", "1", None))
        self.label_66.setText(_translate("MainWindow", "1", None))
        self.label_67.setText(_translate("MainWindow", "1", None))
        self.label_68.setText(_translate("MainWindow", "1", None))
        self.label_69.setText(_translate("MainWindow", "1", None))
        self.label_70.setText(_translate("MainWindow", "1", None))
        self.label_71.setText(_translate("MainWindow", "1", None))
        self.label_72.setText(_translate("MainWindow", "1", None))
        self.label_73.setText(_translate("MainWindow", "1", None))
        self.label_74.setText(_translate("MainWindow", "1", None))
        self.label_75.setText(_translate("MainWindow", "1", None))
        self.label_76.setText(_translate("MainWindow", "1", None))
        self.label_77.setText(_translate("MainWindow", "99", None))
        self.label_78.setText(_translate("MainWindow", "99", None))
        self.label_79.setText(_translate("MainWindow", "99", None))
        self.label_80.setText(_translate("MainWindow", "1", None))
        self.label_81.setText(_translate("MainWindow", "99", None))
        self.label_82.setText(_translate("MainWindow", "1", None))
        self.label_83.setText(_translate("MainWindow", "1", None))
        self.label_84.setText(_translate("MainWindow", "99", None))
        self.label_85.setText(_translate("MainWindow", "99", None))
        self.label_86.setText(_translate("MainWindow", "99", None))
        self.label_87.setText(_translate("MainWindow", "1", None))
        self.label_88.setText(_translate("MainWindow", "1", None))
        self.label_89.setText(_translate("MainWindow", "99", None))
        self.label_90.setText(_translate("MainWindow", "1", None))
        self.label_91.setText(_translate("MainWindow", "1", None))
        self.label_92.setText(_translate("MainWindow", "1", None))
        self.label_93.setText(_translate("MainWindow", "1", None))
        self.label_94.setText(_translate("MainWindow", "1", None))
        self.label_95.setText(_translate("MainWindow", "1", None))
        self.label_96.setText(_translate("MainWindow", "99", None))
        self.label_97.setText(_translate("MainWindow", "99", None))
        self.label_98.setText(_translate("MainWindow", "1", None))
        self.label_99.setText(_translate("MainWindow", "99", None))
        self.label_100.setText(_translate("MainWindow", "1", None))
        self.label_101.setText(_translate("MainWindow", "1", None))
        self.label_102.setText(_translate("MainWindow", "1", None))
        self.label_103.setText(_translate("MainWindow", "99", None))
        self.label_104.setText(_translate("MainWindow", "Other Players", None))
        self.pushButton.setText(_translate("MainWindow", "CINKO", None))
        self.label_109.setText(_translate("MainWindow", "Kate", None))
        self.label_110.setText(_translate("MainWindow", "Jim", None))
        self.label_111.setText(_translate("MainWindow", "Jasmine", None))
        self.label_112.setText(_translate("MainWindow", "Hun", None))

